### ISSUE TITLE
When comeback?

### ISSUE THREAD

**Issue by user6879** [denolanduz/denonent#2]
Waiting for this organization to wake up!

**Comment by katsuki-yuri** [comment]
depends on current maintainers, @shakhzodkudratov. if he refuses to don't anything, it will go on so cuz i transferred project to him, hence he is the only one to rule over this organization (community)... but still i maintain deno's community as a branch inside rust community as i maintain few of my repositories on deno.

**Comment by user6879** [comment]
then i will wait for his answer.

**Comment by shakhzodkudratov** [comment]
i am not maintaining this org anymore, transferred it back to @katsuki-yuri glhf

**Comment by katsuki-yuri** [comment]
accepted!
